# Generated by Django 3.0.5 on 2020-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pic',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
