# Generated by Django 3.0.5 on 2020-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images\\'),
        ),
    ]
