# Generated by Django 3.0.5 on 2020-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='myresume',
            field=models.FileField(blank=True, null=True, upload_to='images\\'),
        ),
    ]
