# Generated by Django 3.0.5 on 2020-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200621_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggetion',
            field=models.TextField(max_length=200),
        ),
    ]
