# Generated by Django 3.0.5 on 2020-06-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200621_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.IntegerField(),
        ),
    ]
